### ISSUE TITLE
Custom reporter in CommonJS project fails after v0.12.0

### ISSUE THREAD

**Issue by avaly** [webpro/knip#23]
Using a custom reporter in a top level project using `"type": "commonjs"` is not possible since v0.12.0 when the ESM migration was done:

```js
module.exports = async function reporter() {
	// ...
};
```

Adding the following log after the `printReport` is defined:

```
console.log('printReport', printReport);
```

Yields the following:

```
printReport [Module: null prototype] { default: [AsyncFunction: reporter] }
```

Running the tool errors like:

```
 file:///home/runner/work/foo/node_modules/knip/dist/cli.js:37
        await printReport({ report, issues, cwd, workingDir, isDev, options: reporterOptions });
              ^

TypeError: printReport is not a function
    at run (file:///home/runner/work/foo/node_modules/knip/dist/cli.js:37:15)
```

This used to work on knip v0.11.0. The log above printed this on that version:

```
printReport [AsyncFunction: reporter]
```

**Comment by avaly** [comment]
@webpro This has regressed in v1.2.0 (most likely in v1.0.0).

**Comment by webpro** [comment]
Oops... there are no "integration" tests yet (meaning only that `cli.ts` module does not have coverage yet) and this isn't trivial to set up (added ticket #44 for this).

For now, this should be fixed again in v1.4.0.
