### ISSUE TITLE
typescript issue with vite plugin

### ISSUE THREAD

**Issue by ljharb** [webpro/knip#567]
I'm getting
```sh
node_modules/knip/dist/plugins/vite/index.d.ts:9:79 - error TS2307: Cannot find module '#p/plugins/vitest/types.ts' or its corresponding type declarations.

9     resolveEntryPaths: import("#p/types/plugins.js").ResolveEntryPaths<import("#p/plugins/vitest/types.ts").ViteConfigOrFn | import("#p/plugins/vitest/types.ts").VitestWorkspaceConfig>;
                                                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/knip/dist/plugins/vite/index.d.ts:9:133 - error TS2307: Cannot find module '#p/plugins/vitest/types.ts' or its corresponding type declarations.

9     resolveEntryPaths: import("#p/types/plugins.js").ResolveEntryPaths<import("#p/plugins/vitest/types.ts").ViteConfigOrFn | import("#p/plugins/vitest/types.ts").VitestWorkspaceConfig>;
                                                                                                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/knip/dist/plugins/vite/index.d.ts:10:71 - error TS2307: Cannot find module '#p/plugins/vitest/types.ts' or its corresponding type declarations.

10     resolveConfig: import("#p/types/plugins.js").ResolveConfig<import("#p/plugins/vitest/types.ts").ViteConfigOrFn | import("#p/plugins/vitest/types.ts").VitestWorkspaceConfig>;
                                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/knip/dist/plugins/vite/index.d.ts:10:125 - error TS2307: Cannot find module '#p/plugins/vitest/types.ts' or its corresponding type declarations.

10     resolveConfig: import("#p/types/plugins.js").ResolveConfig<import("#p/plugins/vitest/types.ts").ViteConfigOrFn | import("#p/plugins/vitest/types.ts").VitestWorkspaceConfig>;
                                                                                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 4 errors in the same file, starting at: node_modules/knip/dist/plugins/vite/index.d.ts:9
```

here: https://github.com/ljharb/unused-files/actions/runs/8370450998/job/22917831503#step:6:33

It started when I updated from v5.0.4 to v5.1.5. Unfortunately `exclude` in tsconfig isn't helping me ignore these.

**Comment by webpro** [comment]
The reason it broke for you is I've introduced a cleaner way to write plugins, and [these subpath imports](https://github.com/webpro/knip/blob/main/packages/knip/package.json#L33-L36) are part of that.

Using Knip in a programmatic way is not supported currently, it might break again.

[Just curious](https://twitter.com/webprolific/status/1768176780152562094), any chance you could share what made you wrap Knip?

**Comment by ljharb** [comment]
the commit linked above your comment is to that project, https://npmjs.com/@ljharb/unused-files

knip didn’t support the concise API i needed, so i wrapped it. It’s clear it’s not supported programmatically since importing any part of it immediately invokes the command-line handling, so i had to hack around that.

It’s fine if there’s nothing you can do about it, and maybe it’s just a typescript bug with subpath imports - it’s just unfortunate because TS won’t even let me explicitly ignore the file.

**Comment by ljharb** [comment]
I don't care about typechecking knip, is the point :-) unfortunately even when i set the max node_modules depth to 0, TS still complains about it.

**Comment by webpro** [comment]
Subpath imports are also a Node.js runtime feature. Going to close this as there currently isn't much Knip can do here, I believe.

**Comment by ljharb** [comment]
@webpro is there any chance you'd be interested in exposing any parts of knip as importable libraries?

**Comment by webpro** [comment]
Maybe it's just bad timing, but I'm currently not interested in widening the API surface area. In general I'd love to be able to spend more time on Knip, but there are limits (I'm looking for sponsors). Mentioned similar statements before:

- https://github.com/webpro/knip/issues/41#issuecomment-1829378882
- https://github.com/webpro/knip/issues/540#issuecomment-2008254880
- https://github.com/webpro/knip/issues/551#issuecomment-2002424076

**Comment by ljharb** [comment]
fwiw, this issue was fixed in v5.9.2. I'm not sure what fixed it, but at least i can unpin now :-)
